### ISSUE TITLE
Requirements.txt is out of date -- causing conflicts

### ISSUE THREAD

**Issue by savraj** [imagekit-developer/imagekit-python#15]
**problem**
Pip can't auto install this library, because it conflicts with other libraries that require a newer version of requests.

**fix**
Change:
https://github.com/imagekit-developer/imagekit-python/blob/master/requirements/requirements.txt
change to `requests>=2.22.0` instead of `requests==2.22.0`

the current version of requests as of this writing is `2.25.1`

thanks

**Comment by ahnv** [comment]
Fixed and Merge to master

**Comment by ahnv** [comment]
Released in [Release 2.2.6](https://pypi.org/project/imagekitio/2.2.6/)

**Comment by savraj** [comment]
guys, THANK YOU!!!
