### ISSUE TITLE
Failed to output transformation in query format instead of url

### ISSUE THREAD

**Issue by Bhupesh-V** [imagekit-developer/imagekit-python#21]
Even after specifying `transformation_position` to be the query, the output is still in URL format

```python
image_url = imagekit.url({
    "path": "/my_image.jpg",
    "url_endpoint": URL_ENDPOINT,
    "transformation": [
      {
        "height": "500",
        "width": "500",
        "crop": "at_least",
      },
    ],
    "transformation_position ": "query"
})
```
**Sample Output**:
```
https://ik.imagekit.io/bhupesh/tr:h-500,w-500,c-at_least/my_image.jpg?ik-sdk-version=python-2.2.8
```

### env
- Python [3.8.10]
- pip [20.0.2]
- Imagekitio [2.2.8]

**Comment by samims** [comment]
Try with "transformation_position" instead of "transformation_position " there is a space in the ending. Please try by removing the  space as above.

**Comment by Bhupesh-V** [comment]
> Try with "transformation_position" instead of "transformation_position " there is a space in the ending. Please try by removing the space as above.

Thanks
Ah damn, I feel so stupid rn 😅
