### ISSUE TITLE
Cache purge

### ISSUE THREAD

**Issue by deshnena** [imagekit-developer/imagekit-python#22]
I have a use case where I want to delete multiple files in a folder 

ex: 

imagekit.purge_cache(file_url="https://ik.imagekit.io/your_imagekit_id/foldername/*")

I want all the files in the folder to be cache purge how can I do that.

currently getting the following error

images were flushed at cdn internal for imagekit service {'error': {'message': 'The URL is not valid for cache purging.', 'help': 'For support kindly contact us at support@imagekit.io .'}, 'response': None}

I followed public doc but isn't much helpful please provide me a direction here:

   -- https://docs.imagekit.io/api-reference/media-api/purge-cache#examples

**Comment by imagekitio** [comment]
The issue is not related to this SDK. Please contact support via the email.
