### ISSUE TITLE
useUniqueFileName not working when uploading files using the sdk 

### ISSUE THREAD

**Issue by jobyid** [imagekit-developer/imagekit-python#24]
```
upload = imagekit.upload(
            file=image_path,
            file_name=image_name,
            options={
                "response_fields": ["is_private_file", "tags"],
                "tags": ["city", "nft"],
                "folder": folder_path,
                "useUniqueFileName": False
            },
        )
```
Produces a invalid options error, but when I remove the useUniqueFileName part it works fine. Any suggestions? 
I have tried using it with the "false" rather then bool.

**Comment by ahnv** [comment]
Hey @jobyid,

Try using `use_unique_file_name`. 
You can find the sample [here](https://github.com/imagekit-developer/imagekit-python/blob/c02ebcca6ee9fbc552b55d3d7ef2e2b4fbc82e49/sample/sample.py)

**Comment by jobyid** [comment]
That worked thanks very much
