### ISSUE TITLE
Returning KeyError for embedded_metadata when uploading with base64

### ISSUE THREAD

**Issue by mooreman11** [imagekit-developer/imagekit-python#35]
This is specific to when I upload the file with Base64 encoding (all the other encodings are not working for me when uploading with File objects from Django). 

`UploadFileResult.py`

```
if embedded_metadata is None or embedded_metadata == {}:
    self.embedded_metadata = EmbeddedMetadata(None, None, None, None)
else:
    if type(embedded_metadata) == EmbeddedMetadata:
        self.embedded_metadata = embedded_metadata
    else:
        self.embedded_metadata: EmbeddedMetadata = EmbeddedMetadata(
            embedded_metadata["x_resolution"],
            embedded_metadata["y_resolution"],
            embedded_metadata["date_created"],
            embedded_metadata["date_timecreated"],
        )
```

I debugged the code and realized that the keys are not the same. I also did not receive keys for `date_created` and `date_timecreated`.
This is an example of the dict `embedded_metadata` from my debugger console: ```embedded_metadata = {'ModifyDate': '0000:00:00 00:00:00', 'XResolution': 72, 'YResolution': 72, 'ImageWidth': 480, 'ImageHeight': 848, 'ImageSize': '480x848', 'Megapixels': 0.407}```

**Comment by imagekitio** [comment]
Fixed in version 3.0.2
